## Numpy
- Array（数组）
- rank 数组维数
- import numpy as np //引入numpy
- a = np.array([1,2,3]) //定义并初始化数组a
- type(a) //查看a的类型
- a.shape //查看a的大小
- a=a.reshape((1,-1)) //第一个1是只有一行，-1是一个占位符
- a = np.zeros((3,3)) //创建行列都是3的元素全为0数组
- a = np.ones((2,3)) //创建行是2列是3的元素全为1数组
- a = np.full((3,3),0) //创建行列都是3的元素全为0数组
- eye（创建单位矩阵）
- a = np.eye(3)
- reshape(1,-1)
这个函数中"-1"表示占位符,根据实际数组自动计算出来
- random.random 从0到1之间随机取值


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
a = a.reshape(2,-1)

ValueError: cannot reshape array of size 3 into shape (2,newaxis)

In [6]:
a = np.array([1,2,3,4,5,6])

In [7]:
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a = a.reshape(2,-1)

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.shape

(2, 3)

In [11]:
a = np.zeros(3,2)

TypeError: data type not understood

In [14]:
a = np.zeros((3,2))

In [15]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
a = np.ones((4,4))

In [17]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
a = np.full((2,2),10)

In [19]:
a


array([[10, 10],
       [10, 10]])

In [20]:
a = np.eye(3)

In [21]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
a = np.eye((3),2)

In [23]:
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [24]:
a = np.eye((3),3)

In [25]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a = np.random.random((3,3))


In [28]:
a

array([[3.94817363e-01, 7.74691214e-04, 6.04969294e-01],
       [7.95760527e-01, 7.12867494e-01, 6.90292753e-01],
       [8.66882775e-01, 4.12760791e-01, 3.87716637e-01]])

In [32]:
a = np.random.random((2,2))

In [33]:
a

array([[0.0913109 , 0.65360216],
       [0.02589721, 0.42649916]])